# This is a simple Python script that interacts with the user to gather personal information and preferences.
firstname = input('What is your first name ?')
print('Hello ' + firstname + '!')
lastname = input('What is your last name ?')
print('Hello ' + firstname + ' ' + lastname + '!')
age = input('How old are you ?') 
studies = input('What field are you studying ?')
university = input('Are you attending which university ?') 
studies_duration = input('How long have you been studying ' + studies + ' ?')
choice_university = input('Why did you choose ' + university + ' ?')
loved_field = input('What is your favorite field ?')
print('I chosed ' + university + ' because it is so famous and I love ' + loved_field + '!')
print('I am ' + age + ' years old and I love studying ' + studies + ' at ' + university + '.')
print('Good Bye ' + firstname + ' ' + lastname + '!') 
